version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "${FRONTEND_PORT:-8123}:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    image: bookstack-sync-spring_bookstack-sync
    container_name: bookstack-sync
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: always
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES:-prod}
      # Add CORS configuration environment variables
      - SPRING_WEB_CORS_ALLOWED-ORIGINS=*
      - SPRING_WEB_CORS_ALLOWED-METHODS=GET,POST,PUT,DELETE,OPTIONS
      - SPRING_WEB_CORS_ALLOWED-HEADERS=*
      - SPRING_WEB_CORS_ALLOW-CREDENTIALS=false
      - SPRING_WEB_CORS_MAX-AGE=3600
    # Uncomment if you need volumes for data persistence
    # volumes:
    #   - backend-data:/data

networks:
  app-network:
    driver: bridge
    # Explicitly set the name to avoid name conflicts
    name: bookstack_network

# Uncomment if you need volumes
# volumes:
#   backend-data: