version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "8123:80"
    restart: always

networks:
  default:
    driver: bridge